### ISSUE TITLE
Uncaught TypeError: Cannot read property 'spawn' of undefined

### ISSUE THREAD

**Issue by liuxh0** [sprinteins/ghost#76]
I have this error in browser when running `yarn dev`.

![image](https://user-images.githubusercontent.com/15948574/65386902-5dedf780-dd41-11e9-8b9b-2a8e5cec5f4d.png)

I cloned the repository and ran `yarn install` successfully. I have yarn 1.17.3, node 11.11.0 under macOS 10.14.6 installed.

**Comment by L4B0MB4** [comment]
This is because "spawn" is part of the native nodejs library. It´s not available in the browser (Ghost is not designed to work in the browser). You have to run two scripts in parallel "yarn dev" and "yarn start-dev". The first one builds the react part of this project and the second one starts electron. We are working on an more intuitive solution.

**Comment by liuxh0** [comment]
Thanks. I thought "Run local web development server" means running in browser.

**Comment by L4B0MB4** [comment]
@liuxh0 I see how this is confusing. We will rename that.

**Comment by N3ol4N** [comment]
We added a comment to the README to make it more clear. #78
